<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; }
        h1 { font-size: 15px; margin-bottom: 4px; }
        .meta { font-size: 10px; color: #666; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f0f0f0; font-weight: bold; text-align: left; padding: 5px 7px; border: 1px solid #ccc; font-size: 10px; }
        td { padding: 4px 7px; border: 1px solid #ddd; vertical-align: top; }
        tr:nth-child(even) td { background: #fafafa; }
        .footer { margin-top: 20px; font-size: 9px; color: #999; border-top: 1px solid #ddd; padding-top: 6px; }
        .empty { text-align: center; color: #999; padding: 16px; }
    </style>
</head>
<body>
    <h1>Attendance Report</h1>
    <div class="meta">
        Type: {{ ucfirst(str_replace('_', ' ', $type)) }}
        &nbsp;|&nbsp;
        Period: {{ $from }} to {{ $to }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Student</th>
                <th>Roll No</th>
                <th>Course</th>
                <th>Session Date</th>
                <th>Status</th>
                <th>Marked At</th>
                <th>Risk Score</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
            <tr>
                <td>{{ $record->student?->user?->name ?? '—' }}</td>
                <td>{{ $record->student?->roll_no ?? '—' }}</td>
                <td>{{ $record->session?->course?->code ?? '—' }}</td>
                <td>{{ $record->session?->started_at?->format('Y-m-d') ?? '—' }}</td>
                <td>{{ $record->status->value }}</td>
                <td>{{ $record->marked_at?->format('Y-m-d H:i') ?? '—' }}</td>
                <td>{{ $record->risk_score }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="empty">No records found for this period.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by QR Attendance System on {{ $generatedAt }}
    </div>
</body>
</html>
